(()=>{'use strict';
const $=id=>document.getElementById(id), clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const E={dot:$('statusDot'),status:$('statusText'),log:$('log'),drop:$('dropzone'),input:$('fileInput'),wrap:$('previewWrap'),video:$('video'),canvas:$('previewCanvas'),scope:$('scope'),meta:$('fileMeta'),play:$('playBtn'),seek:$('seek'),time:$('timeText'),badge:$('darkBadge'),sliders:$('sliders'),export:$('exportBtn'),cancel:$('cancelBtn'),reset:$('resetBtn'),progress:$('progressWrap'),bar:$('progressBar'),result:$('resultCard'),out:$('outputVideo'),download:$('downloadLink'),outputMeta:$('outputMeta'),quality:$('quality'),fps:$('fps'),applyMode:$('applyMode'),rangeFields:$('rangeFields'),rangeStart:$('rangeStart'),rangeEnd:$('rangeEnd'),rangeHint:$('rangeHint'),rangeName:$('rangeName'),rangeList:$('rangeList'),saveRange:$('saveRange'),cancelRangeEdit:$('cancelRangeEdit'),useRangeStart:$('useRangeStart'),useRangeEnd:$('useRangeEnd'),referenceTime:$('referenceTime'),useCurrentTime:$('useCurrentTime'),applyReference:$('applyReference'),clearReference:$('clearReference'),matchStrength:$('matchStrength'),referenceState:$('referenceState')};
const defs=[['Işık','exposure','Pozlama',-100,100,0],['Işık','contrast','Kontrast',-100,100,0],['Işık','shadows','Gölgeler',-100,100,0],['Işık','highlights','Parlak alanlar',-100,100,0],['Renk','saturation','Doygunluk',-100,100,0],['Renk','vibrance','Canlılık',-100,100,0],['Renk','temperature','Sıcaklık',-100,100,0],['Renk','tint','Ton',-100,100,0],['Detay','sharpen','Netlik',0,100,0],['Detay','denoise','Gürültü azaltma',0,100,0],['Ses','volume','Ses yükseltme',0,400,100],['Ses','compress','Dinamik sıkıştırma',0,100,0]];
const p={}; let gl,program,tex,loc={},fileURL=null,outURL=null,busy=false,cancelled=false,raf=0,reference=null,lastStats=null,analysisCanvas=document.createElement('canvas'),analysisCtx=analysisCanvas.getContext('2d',{willReadFrequently:true}),audioCtx,sourceNode,gainNode,compressor,destination,ranges=[],editingRangeId=null,draftRange=false,rangeSeq=1;
function log(s){E.log.textContent=`${new Date().toLocaleTimeString()}  ${s}\n`+E.log.textContent}function status(s,c=''){E.status.textContent=s;E.dot.className=c}function fmt(t){t=Math.max(0,t||0);return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`}
function controls(){let g='';for(const [group,id,label,min,max,val] of defs){p[id]=val;if(group!==g){g=group;E.sliders.insertAdjacentHTML('beforeend',`<div class="group"><div class="group-title">${group}</div><div id="g-${group}"></div></div>`)}$(`g-${group}`).insertAdjacentHTML('beforeend',`<div class="slider"><label>${label}<output id="o-${id}">${id==='volume'?val+'%':val}</output></label><input id="${id}" type="range" min="${min}" max="${max}" value="${val}"></div>`);$(id).oninput=e=>{p[id]=+e.target.value;$(`o-${id}`).value=id==='volume'?p[id]+'%':p[id];if(E.applyMode.value==='multi'&&id!=='volume'&&id!=='compress')draftRange=true;updateAudio()}}}
function setP(id,v){const d=defs.find(x=>x[1]===id);v=clamp(Math.round(v),d[3],d[4]);p[id]=v;$(id).value=v;$(`o-${id}`).value=id==='volume'?v+'%':v}
const presets={auto:{exposure:10,contrast:8,shadows:15,highlights:-8,saturation:5,vibrance:10},cinematic:{exposure:-3,contrast:22,shadows:8,highlights:-18,saturation:-8,vibrance:12,temperature:-6},vivid:{exposure:5,contrast:15,saturation:22,vibrance:28,sharpen:16},warm:{exposure:5,contrast:8,saturation:8,temperature:24,tint:4},reset:{}};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const name=b.dataset.preset;for(const d of defs)setP(d[1],d[1]==='volume'?100:0);Object.entries(presets[name]).forEach(([k,v])=>setP(k,v));reference=null;syncReference();if(E.applyMode.value==='multi')draftRange=true;log(`Ön ayar uygulandı: ${name}`)});
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
function initGL(){gl=E.canvas.getContext('webgl',{preserveDrawingBuffer:true,alpha:false});if(!gl)throw Error('WebGL desteği yok.');const vs=`attribute vec2 a;varying vec2 v;void main(){v=(a+1.0)*.5;gl_Position=vec4(a,0,1);}`;const fs=`precision highp float;uniform sampler2D t;uniform vec2 px;uniform float exposure,contrast,saturation,vibrance,temp,tint,shadows,highlights,sharp,apply;uniform vec3 matchGain;varying vec2 v;vec3 sat(vec3 c,float s){float l=dot(c,vec3(.2126,.7152,.0722));return mix(vec3(l),c,s);}void main(){vec3 c=texture2D(t,vec2(v.x,1.0-v.y)).rgb;vec3 base=c;if(sharp>0.001){vec3 n=texture2D(t,vec2(v.x,1.0-v.y)+vec2(0.0,px.y)).rgb;vec3 s=texture2D(t,vec2(v.x,1.0-v.y)-vec2(0.0,px.y)).rgb;vec3 e=texture2D(t,vec2(v.x,1.0-v.y)+vec2(px.x,0.0)).rgb;vec3 w=texture2D(t,vec2(v.x,1.0-v.y)-vec2(px.x,0.0)).rgb;c+=((c*4.0-n-s-e-w)*sharp);}c*=pow(2.0,exposure);c=(c-.5)*contrast+.5;c=mix(c,c*matchGain,apply);float l=dot(c,vec3(.2126,.7152,.0722));c+=vec3(shadows*(1.0-smoothstep(0.0,.55,l)));c-=vec3(highlights*smoothstep(.45,1.0,l));c=sat(c,saturation);float mx=max(c.r,max(c.g,c.b)),mn=min(c.r,min(c.g,c.b));c=sat(c,1.0+vibrance*(1.0-(mx-mn)));c+=vec3(temp*.08,-abs(temp)*.015,-temp*.08);c+=vec3(tint*.05,-tint*.05,tint*.05);c=clamp(c,0.0,1.0);gl_FragColor=vec4(mix(base,c,apply),1);}`;program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);['px','exposure','contrast','saturation','vibrance','temp','tint','shadows','highlights','sharp','apply','matchGain'].forEach(k=>loc[k]=gl.getUniformLocation(program,k));tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);status('GPU hazır','ready');log('WebGL renk motoru hazır.');}
function stats(){if(!E.video.videoWidth)return null;analysisCanvas.width=48;analysisCanvas.height=48;analysisCtx.drawImage(E.video,0,0,48,48);const d=analysisCtx.getImageData(0,0,48,48).data;let r=0,g=0,b=0,l=0,l2=0,n=d.length/4;for(let i=0;i<d.length;i+=4){const R=d[i]/255,G=d[i+1]/255,B=d[i+2]/255,L=.2126*R+.7152*G+.0722*B;r+=R;g+=G;b+=B;l+=L;l2+=L*L}l/=n;return {r:r/n,g:g/n,b:b/n,l,std:Math.sqrt(Math.max(0,l2/n-l*l))}}
function matchGain(s,ref=reference,strength=+E.matchStrength.value){if(!ref||!s)return [1,1,1];const lum=clamp(ref.l/Math.max(.04,s.l),.72,1.38);return [clamp((ref.r/Math.max(.04,s.r))*.55+lum*.45,.65,1.5),clamp((ref.g/Math.max(.04,s.g))*.55+lum*.45,.65,1.5),clamp((ref.b/Math.max(.04,s.b))*.55+lum*.45,.65,1.5)].map(x=>1+(x-1)*strength)}
function visualSnapshot(){const out={};for(const d of defs)if(!['volume','compress'].includes(d[1]))out[d[1]]=p[d[1]];return out}
function neutralVisual(){const out={};for(const d of defs)if(!['volume','compress'].includes(d[1]))out[d[1]]=0;return out}
function cloneReference(r){return r?{r:r.r,g:r.g,b:r.b,l:r.l,std:r.std}:null}
function currentDraftRange(t){if(!draftRange||E.applyMode.value!=='multi')return null;const a=+E.rangeStart.value,b=+E.rangeEnd.value;if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a||t<a||t>b)return null;return {id:'draft',start:a,end:b,settings:visualSnapshot(),reference:cloneReference(reference),strength:+E.matchStrength.value}}
function activeRangeAt(t){let found=null;for(const r of ranges)if(t>=r.start&&t<=r.end)found=r;return found}
function renderProfile(t){if(E.applyMode.value==='full')return {apply:1,settings:p,reference,strength:+E.matchStrength.value,id:'full'};const draft=currentDraftRange(t);if(draft)return {...draft,apply:1};const r=activeRangeAt(t);if(r)return {...r,apply:1};return {apply:0,settings:neutralVisual(),reference:null,strength:0,id:null}}
function draw(){if(E.video.readyState<2)return;lastStats=stats()||lastStats;const profile=renderProfile(E.video.currentTime),q=profile.settings,gain=matchGain(lastStats,profile.reference,profile.strength);gl.viewport(0,0,E.canvas.width,E.canvas.height);gl.bindTexture(gl.TEXTURE_2D,tex);try{gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,E.video)}catch(_){return}gl.uniform2f(loc.px,1/E.canvas.width,1/E.canvas.height);gl.uniform1f(loc.exposure,(q.exposure||0)/100*1.2);gl.uniform1f(loc.contrast,1+(q.contrast||0)/100);gl.uniform1f(loc.saturation,1+(q.saturation||0)/100);gl.uniform1f(loc.vibrance,(q.vibrance||0)/100*.8);gl.uniform1f(loc.temp,(q.temperature||0)/100);gl.uniform1f(loc.tint,(q.tint||0)/100);gl.uniform1f(loc.shadows,(q.shadows||0)/100*.25);gl.uniform1f(loc.highlights,(q.highlights||0)/100*.25);gl.uniform1f(loc.sharp,(q.sharpen||0)/100*.35);gl.uniform1f(loc.apply,profile.apply);gl.uniform3f(loc.matchGain,gain[0],gain[1],gain[2]);gl.drawArrays(gl.TRIANGLES,0,6);updateScope();highlightActiveRange(profile.id);E.seek.value=E.video.duration?Math.round(E.video.currentTime/E.video.duration*1000):0;E.time.textContent=`${fmt(E.video.currentTime)} / ${fmt(E.video.duration)}`;E.bar.style.width=busy?`${clamp(E.video.currentTime/E.video.duration*100,0,100)}%`:E.bar.style.width}
function loop(){draw();if(!E.video.paused&&!E.video.ended)raf=requestAnimationFrame(loop)}
function updateScope(){const c=E.scope.getContext('2d'),w=E.scope.width,h=E.scope.height;c.clearRect(0,0,w,h);if(!lastStats)return;const x=lastStats.l*w;c.fillStyle='#3ddc97';c.fillRect(0,h-lastStats.l*h,w/3,lastStats.l*h);c.fillStyle='#5aa9ff';c.fillRect(w/3,h-lastStats.std*h*3,w/3,lastStats.std*h*3);c.fillStyle='#e8edf2';c.fillRect(2*w/3,h-x/w*h,w/3,x/w*h);E.badge.classList.toggle('hidden',lastStats.l>.28)}
function setupAudio(){if(sourceNode)return;audioCtx=new (window.AudioContext||window.webkitAudioContext)();sourceNode=audioCtx.createMediaElementSource(E.video);gainNode=audioCtx.createGain();compressor=audioCtx.createDynamicsCompressor();destination=audioCtx.createMediaStreamDestination();sourceNode.connect(gainNode).connect(compressor);compressor.connect(destination);compressor.connect(audioCtx.destination);updateAudio()}
function updateAudio(){if(!gainNode)return;gainNode.gain.value=p.volume/100;compressor.threshold.value=-10-p.compress*.3;compressor.ratio.value=1+p.compress*.11}
async function load(f){if(!f||!f.type.startsWith('video/'))return log('Geçerli bir video seçin.');ranges=[];resetRangeEditor();renderRangeList();if(fileURL)URL.revokeObjectURL(fileURL);fileURL=URL.createObjectURL(f);E.video.src=fileURL;E.video.load();await new Promise((res,rej)=>{E.video.onloadedmetadata=res;E.video.onerror=()=>rej(Error('Tarayıcı videoyu açamadı. AV1 donanım/tarayıcı desteğini kontrol edin.'))});E.canvas.width=Math.max(2,Math.floor(E.video.videoWidth/2)*2);E.canvas.height=Math.max(2,Math.floor(E.video.videoHeight/2)*2);E.rangeEnd.value=E.video.duration.toFixed(2);E.referenceTime.max=E.video.duration;E.wrap.classList.remove('hidden');E.export.disabled=false;E.applyReference.disabled=false;E.saveRange.disabled=false;E.meta.textContent=`${f.name} · ${(f.size/1048576).toFixed(2)} MB · ${E.video.videoWidth}×${E.video.videoHeight} · ${E.video.duration.toFixed(2)} sn`;E.video.currentTime=0;await new Promise(r=>E.video.onseeked=r);draw();setupAudio();log('Video tarayıcı çözücüsüyle açıldı.');}
E.drop.onclick=()=>E.input.click();E.drop.ondragover=e=>{e.preventDefault();E.drop.classList.add('drag')};E.drop.ondragleave=()=>E.drop.classList.remove('drag');E.drop.ondrop=e=>{e.preventDefault();E.drop.classList.remove('drag');load(e.dataTransfer.files[0]).catch(e=>log(e.message))};E.input.onchange=e=>load(e.target.files[0]).catch(e=>log(e.message));
E.play.onclick=async()=>{setupAudio();await audioCtx.resume();if(E.video.paused){await E.video.play();E.play.textContent='Duraklat';loop()}else{E.video.pause();E.play.textContent='Oynat';cancelAnimationFrame(raf)}};E.video.onended=()=>{E.play.textContent='Oynat';cancelAnimationFrame(raf)};E.seek.oninput=()=>{E.video.currentTime=E.video.duration*(+E.seek.value/1000)};E.video.onseeked=draw;
E.useCurrentTime.onclick=()=>E.referenceTime.value=E.video.currentTime.toFixed(2);E.applyReference.onclick=async()=>{const t=clamp(+E.referenceTime.value,0,E.video.duration);const old=E.video.currentTime,paused=E.video.paused;E.video.pause();E.video.currentTime=t;await new Promise(r=>E.video.onseeked=r);reference=stats();E.video.currentTime=old;await new Promise(r=>E.video.onseeked=r);if(!paused){await E.video.play();loop()}syncReference();if(E.applyMode.value==='multi')draftRange=true;log(`Referans kare alındı: ${t.toFixed(2)} sn.`)};E.clearReference.onclick=()=>{reference=null;syncReference();if(E.applyMode.value==='multi')draftRange=true;log('Referans renk eşleme kaldırıldı.')};function syncReference(){E.clearReference.disabled=!reference;E.referenceState.value=reference?`Aktif · Luma ${(reference.l*100).toFixed(1)}%`:'Referans seçilmedi'}
function rangeSummary(r){const s=r.settings,parts=[];[['exposure','Poz'],['contrast','Kon'],['shadows','Göl'],['highlights','Par'],['saturation','Doy'],['temperature','Isı']].forEach(([k,n])=>{if(s[k])parts.push(`${n} ${s[k]>0?'+':''}${s[k]}`)});if(r.reference)parts.push(`Referans ${Math.round(r.strength*100)}%`);return parts.length?parts.join(' · '):'Nötr renk ayarı'}
function renderRangeList(){if(!ranges.length){E.rangeList.innerHTML='<div class="range-empty">Henüz zaman aralığı eklenmedi.</div>';return}E.rangeList.innerHTML=ranges.map((r,i)=>`<div class="range-item" data-range-id="${r.id}"><div class="range-item-head"><div><div class="range-item-title">${escapeHtml(r.name||`Aralık ${i+1}`)}</div><span class="range-item-time">${r.start.toFixed(2)} – ${r.end.toFixed(2)} sn</span></div><span class="range-index">${i+1}</span></div><div class="range-item-summary">${escapeHtml(rangeSummary(r))}</div><div class="range-item-actions"><button type="button" class="button" data-action="go">Git</button><button type="button" class="button" data-action="edit">Düzenle</button><button type="button" class="button danger" data-action="delete">Sil</button></div></div>`).join('')}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function highlightActiveRange(id){document.querySelectorAll('.range-item').forEach(x=>x.classList.toggle('active',String(x.dataset.rangeId)===String(id)))}
function resetRangeEditor(){editingRangeId=null;draftRange=false;E.rangeName.value='';E.cancelRangeEdit.classList.add('hidden');E.saveRange.textContent='Mevcut ayarlarla aralık ekle'}
function loadRangeEditor(r){editingRangeId=r.id;draftRange=true;E.rangeStart.value=r.start.toFixed(2);E.rangeEnd.value=r.end.toFixed(2);E.rangeName.value=r.name||'';for(const [k,v] of Object.entries(r.settings))setP(k,v);reference=cloneReference(r.reference);E.matchStrength.value=String(r.strength);syncReference();E.cancelRangeEdit.classList.remove('hidden');E.saveRange.textContent='Aralık ayarlarını güncelle';E.video.currentTime=r.start;draw()}
E.applyMode.onchange=()=>{const multi=E.applyMode.value==='multi';E.rangeFields.classList.toggle('hidden',!multi);E.rangeHint.textContent=multi?'Her zaman aralığı kendi renk ve referans ayarını kullanır; boş bölümler orijinal kalır.':'Renk ayarları videonun tamamına uygulanır.';draftRange=multi;draw()};
E.rangeStart.oninput=E.rangeEnd.oninput=()=>{draftRange=true;draw()};E.rangeName.oninput=()=>draftRange=true;E.matchStrength.onchange=()=>{if(E.applyMode.value==='multi')draftRange=true;draw()};
E.useRangeStart.onclick=()=>{E.rangeStart.value=E.video.currentTime.toFixed(2);draftRange=true;draw()};E.useRangeEnd.onclick=()=>{E.rangeEnd.value=E.video.currentTime.toFixed(2);draftRange=true;draw()};
E.saveRange.onclick=()=>{const a=+E.rangeStart.value,b=+E.rangeEnd.value;if(!Number.isFinite(a)||!Number.isFinite(b)||a<0||b<=a||b>E.video.duration+.01){log('Geçersiz aralık: başlangıç bitişten küçük olmalı ve video süresini aşmamalı.');return}const item={id:editingRangeId||rangeSeq++,name:E.rangeName.value.trim(),start:a,end:b,settings:visualSnapshot(),reference:cloneReference(reference),strength:+E.matchStrength.value};if(editingRangeId){const i=ranges.findIndex(x=>x.id===editingRangeId);if(i>=0)ranges[i]=item;log(`Aralık güncellendi: ${a.toFixed(2)}–${b.toFixed(2)} sn.`)}else{ranges.push(item);log(`Yeni aralık eklendi: ${a.toFixed(2)}–${b.toFixed(2)} sn.`)}ranges.sort((x,y)=>x.start-y.start||x.id-y.id);resetRangeEditor();renderRangeList();draw()};
E.cancelRangeEdit.onclick=()=>{resetRangeEditor();renderRangeList();draw()};
E.rangeList.onclick=e=>{const btn=e.target.closest('button[data-action]'),item=e.target.closest('.range-item');if(!btn||!item)return;const id=+item.dataset.rangeId,r=ranges.find(x=>x.id===id);if(!r)return;if(btn.dataset.action==='go'){E.video.currentTime=r.start;draw()}else if(btn.dataset.action==='edit')loadRangeEditor(r);else if(btn.dataset.action==='delete'){ranges=ranges.filter(x=>x.id!==id);if(editingRangeId===id)resetRangeEditor();renderRangeList();draw();log('Zaman aralığı silindi.')}};
function mime(){return ['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x))||''}
E.export.onclick=async()=>{if(busy||!fileURL)return;const m=mime();if(!m)return log('Tarayıcı uygun video kodlayıcı sağlamıyor.');busy=true;cancelled=false;E.export.disabled=true;E.cancel.classList.remove('hidden');E.progress.classList.remove('hidden');status('GPU render yapıyor','busy');if(outURL){URL.revokeObjectURL(outURL);outURL=null}const was=E.video.currentTime;try{setupAudio();await audioCtx.resume();E.video.pause();E.video.currentTime=0;await new Promise(r=>E.video.onseeked=r);const stream=E.canvas.captureStream(+E.fps.value);destination.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const chunks=[],rec=new MediaRecorder(stream,{mimeType:m,videoBitsPerSecond:+E.quality.value,audioBitsPerSecond:192000});rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);const stopped=new Promise((res,rej)=>{rec.onstop=res;rec.onerror=e=>rej(e.error||Error('MediaRecorder hatası'))});rec.start(1000);await E.video.play();loop();await new Promise((res,rej)=>{const chk=()=>{if(cancelled){res();return}if(E.video.ended){res();return}setTimeout(chk,100)};chk();E.video.onerror=()=>rej(Error('Render sırasında video çözülemedi.'))});E.video.pause();draw();rec.stop();await stopped;stream.getTracks().forEach(t=>t.stop());if(cancelled)throw Error('İşlem iptal edildi.');const blob=new Blob(chunks,{type:m});if(blob.size<1024)throw Error(`Render boş çıktı üretti (${blob.size} byte).`);outURL=URL.createObjectURL(blob);E.out.src=outURL;E.download.href=outURL;const mp4=m.startsWith('video/mp4');E.download.download=mp4?'vidagrade-export.mp4':'vidagrade-export.webm';E.download.classList.remove('disabled-link');E.result.classList.remove('hidden');E.outputMeta.className='meta output-ok';E.outputMeta.textContent=`GPU render tamamlandı · ${(blob.size/1048576).toFixed(2)} MB · ${mp4?'MP4':'WebM'}`;E.bar.style.width='100%';log(`Render tamamlandı: ${(blob.size/1048576).toFixed(2)} MB.`)}catch(e){E.outputMeta.className='meta output-error';E.outputMeta.textContent=e.message;E.result.classList.remove('hidden');E.download.classList.add('disabled-link');log('Render hatası: '+e.message)}finally{E.video.currentTime=was;busy=false;E.export.disabled=false;E.cancel.classList.add('hidden');E.progress.classList.add('hidden');status('GPU hazır','ready')}};
E.cancel.onclick=()=>{cancelled=true;E.video.pause();log('Render iptal isteği alındı.')};E.reset.onclick=()=>document.querySelector('[data-preset="reset"]').click();window.onbeforeunload=()=>{if(fileURL)URL.revokeObjectURL(fileURL);if(outURL)URL.revokeObjectURL(outURL)};
try{controls();initGL();renderRangeList()}catch(e){status('GPU hatası');log(e.message)}
})();
